version: "3"

services:

  ## frontend
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/usr/app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - collab
      - matching
      - room
      - question
      - user

  ## backend
  pubsub:
    build: 
      dockerfile: Dockerfile
      context: ./backend/pubsub-service
    restart: always
    ports:
      - "8004:8004"
    expose:
      - "8004"

  collab:
    build: 
      dockerfile: Dockerfile
      context: ./backend/collab-service
    restart: always
    ports:
      - "8005:8005"
    expose:
      - "8005"
    depends_on:
      - pubsub
  
  matching:
    build: 
      dockerfile: Dockerfile
      context: ./backend/matching-service
    restart: always
    ports:
      - "8001:8001"
    expose:
      - "8001"
    depends_on:
      - pubsub

  room:
    build: 
      dockerfile: Dockerfile
      context: ./backend/room-service
    restart: always
    ports:
      - "8002:8002"
    expose:
      - "8002"
    depends_on:
      - pubsub

  question:
    build: 
      dockerfile: Dockerfile
      context: ./backend/question-service
    restart: always
    ports:
      - "8003:8003"
    expose:
      - "8003"

  user:
    build: 
      dockerfile: Dockerfile
      context: ./backend/user-service
    restart: always
    ports:
      - "8393:8393"
    expose:
      - "8393"
