# pull official base image
FROM node:alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci

# add app
COPY . ./
RUN cat .env | tail -n +2 | tee .env.dev
RUN echo "ENV=PROD" >> .env.dev
RUN mv -f .env.dev .env

# start app
CMD ["npm", "run", "test"]
