name: Run CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Run tests
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_wait_seconds: 15
        command: |
          echo "${{ secrets.collab }}" > ./backend/collab-service/.env
          echo "${{ secrets.matching }}" > ./backend/matching-service/.env
          echo "${{ secrets.pubsub }}" > ./backend/pubsub-service/.env
          echo "${{ secrets.question }}" > ./backend/question-service/.env
          echo "${{ secrets.room }}" > ./backend/room-service/.env
          echo "${{ secrets.user }}" > ./backend/user-service/.env
          echo "${{ secrets.frontend }}" > ./frontend/.env
          ./run-tests.sh
